export const PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard:view',
  VEHICLES_VIEW: 'vehicles:view',
  VEHICLES_CREATE: 'vehicles:create',
  VEHICLES_EDIT: 'vehicles:edit',
  VEHICLES_DELETE: 'vehicles:delete',
  TRACKING_VIEW: 'tracking:view',
  TRACKING_EXPORT: 'tracking:export',
  DRIVERS_VIEW: 'drivers:view',
  DRIVERS_CREATE: 'drivers:create',
  DRIVERS_EDIT: 'drivers:edit',
  MAINTENANCE_VIEW: 'maintenance:view',
  MAINTENANCE_MANAGE: 'maintenance:manage',
  FINANCE_VIEW: 'finance:view',
  FINANCE_MANAGE: 'finance:manage',
  COMPLIANCE_VIEW: 'compliance:view',
  COMPLIANCE_MANAGE: 'compliance:manage',
  REPORTS_VIEW: 'reports:view',
  REPORTS_EXPORT: 'reports:export',
  SETTINGS_MANAGE: 'settings:manage',
  USERS_MANAGE: 'users:manage',
  INTEGRATIONS_MANAGE: 'integrations:manage',
  ALERTS_MANAGE: 'alerts:manage'
} as const;

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  super_admin: Object.values(PERMISSIONS),
  fleet_manager: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.VEHICLES_VIEW,
    PERMISSIONS.VEHICLES_CREATE,
    PERMISSIONS.VEHICLES_EDIT,
    PERMISSIONS.TRACKING_VIEW,
    PERMISSIONS.TRACKING_EXPORT,
    PERMISSIONS.DRIVERS_VIEW,
    PERMISSIONS.DRIVERS_CREATE,
    PERMISSIONS.DRIVERS_EDIT,
    PERMISSIONS.MAINTENANCE_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.COMPLIANCE_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.ALERTS_MANAGE
  ],
  operator: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.VEHICLES_VIEW,
    PERMISSIONS.TRACKING_VIEW,
    PERMISSIONS.DRIVERS_VIEW,
    PERMISSIONS.ALERTS_MANAGE
  ],
  maintenance_analyst: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.VEHICLES_VIEW,
    PERMISSIONS.MAINTENANCE_VIEW,
    PERMISSIONS.MAINTENANCE_MANAGE,
    PERMISSIONS.COMPLIANCE_VIEW
  ],
  finance: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.FINANCE_VIEW, PERMISSIONS.FINANCE_MANAGE, PERMISSIONS.REPORTS_VIEW],
  driver: [PERMISSIONS.DASHBOARD_VIEW],
  auditor: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.VEHICLES_VIEW,
    PERMISSIONS.TRACKING_VIEW,
    PERMISSIONS.DRIVERS_VIEW,
    PERMISSIONS.MAINTENANCE_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.COMPLIANCE_VIEW,
    PERMISSIONS.REPORTS_VIEW
  ]
};
